version: "3.8"

services:

  app:
    container_name: whisky-app
    command: sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/whisky
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://whisky:whisky@database:5432/whisky
      - SECRET_STR=5fd98d2ec0d2014d33f9ae008ff724da0901bc5172e7cbf1da19d29c264dd472
      - TOKEN_TYPE=Bearer
      - EXP_ACCESS_TOKEN=15
      - EXP_REFRESH_TOKEN=43200
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.18
    hostname: database
    container_name: whisky-db
    environment:
      - POSTGRES_USER=whisky
      - POSTGRES_PASSWORD=whisky
      - POSTGRES_DB=whisky
      - POSTGRES_HOST_AUTH_METHOD=trust
