"""empty message

Revision ID: f6eb6e60bbec
Revises: 
Create Date: 2023-08-11 13:38:41.936125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6eb6e60bbec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=64), nullable=False),
    sa.Column('descr', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('price > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('shop_category',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('product_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=128), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    op.drop_table('shop_category')
    op.drop_table('product')
    # ### end Alembic commands ###
